version: '3.8'
name: 'ressource'
services:
  apache:
    build:
      context: .docker/apache
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        DOCKER_DNS: ${DOCKER_DNS}
    container_name: ${DOCKER_CONTAINER_NAME}_apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ./..:/home/wwwroot/${DOCKER_DIR_PROJECT}
    depends_on:
      - php
    environment:
      DOCKER_DNS: ${DOCKER_DNS}
      DOCKER_DIR_PROJECT: ${DOCKER_DIR_PROJECT}
      DOCKER_CONTAINER_NAME: ${DOCKER_CONTAINER_NAME}

  mariadb:
    image: mariadb:latest
    container_name: ${DOCKER_CONTAINER_NAME}_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}

  php:
    build:
      context: .docker/php
      args:
        DOCKER_DIR_PROJECT: ${DOCKER_DIR_PROJECT}
        NODE_VERSION: ${NODE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${DOCKER_CONTAINER_NAME}_php
    volumes:
      - ./..:/home/wwwroot/${DOCKER_DIR_PROJECT}
    environment:
      - maildev_host=${DOCKER_CONTAINER_NAME}_maildev
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DOCKER_DNS=${DOCKER_DNS}
      - DB_PORT=${DB_PORT}
      - DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}
    links:
      - mariadb
    depends_on:
      - maildev
      - mariadb

  phpmyadmin:
    build:
      context: .docker/phpmyadmin
    container_name: ${DOCKER_CONTAINER_NAME}_phpmyadmin
    volumes:
      - .docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 81:80
      - 444:443
    links:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${DATABASE_PASSWORD}
      - PMA_PORT=${DB_PORT}
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=6096M
      - MAX_EXECUTION_TIME=6000

  maildev:
    image: maildev/maildev
    container_name: ${DOCKER_CONTAINER_NAME}_maildev
    ports:
      - 1080:1080

